package com.zerogravity.myapp.ai.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;

/**
 * Summary data generated by Gemini AI
 * Contains overview, key insights, and recommendations
 */
@Schema(description = "AI-generated summary data")
public class SummaryData {

	@Schema(description = "Overall summary of the emotion period", example = "This week was generally positive...")
	private String overview;

	@Schema(description = "Key insights extracted from emotion data", example = "[\"Stress peaks on weekdays\", \"Weekend recovery pattern\"]")
	private List<String> keyInsights;

	@Schema(description = "Personalized recommendations for emotion management", example = "[\"Try meditation on Wednesday evenings\"]")
	private List<String> recommendations;

	// Constructors
	public SummaryData() {}

	public SummaryData(String overview, List<String> keyInsights, List<String> recommendations) {
		this.overview = overview;
		this.keyInsights = keyInsights;
		this.recommendations = recommendations;
	}

	// Getters and Setters
	public String getOverview() {
		return overview;
	}

	public void setOverview(String overview) {
		this.overview = overview;
	}

	public List<String> getKeyInsights() {
		return keyInsights;
	}

	public void setKeyInsights(List<String> keyInsights) {
		this.keyInsights = keyInsights;
	}

	public List<String> getRecommendations() {
		return recommendations;
	}

	public void setRecommendations(List<String> recommendations) {
		this.recommendations = recommendations;
	}

	@Override
	public String toString() {
		return "SummaryData{" +
			"overview='" + overview + '\'' +
			", keyInsights=" + keyInsights +
			", recommendations=" + recommendations +
			'}';
	}
}
