# 감정 정보
CREATE TABLE emotion (
    emotion_id VARCHAR(36) NOT NULL PRIMARY KEY,
    emotion_type VARCHAR(100) NOT NULL,
    emotion_level INT NOT NULL,
    color_scheme VARCHAR(100) NOT NULL,
    shape_name VARCHAR(100) NOT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

# 감정 상세 정보
CREATE TABLE emotion_reason (
    emotion_reason_id VARCHAR(36) NOT NULL KEY,
	emotion_reason VARCHAR(100) NOT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);