DROP DATABASE IF EXISTS spaceout;
CREATE DATABASE spaceout DEFAULT CHARACTER SET utf8mb4;

USE spaceout;

# 메인 3D 오브젝트
CREATE TABLE object (
    object_id VARCHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    model_url VARCHAR(255) NOT NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);